[package]
name = "day-4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error = "0.1.9"
itertools = "0.12.0"
miette = "5.10.0"
nom = "7.1.3"
