[package]
name = "day-10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.24.2"
itertools = "0.12.0"
nom = "7.1.3"
nom_locate = "4.2.0"
tracing = "0.1.40"
winnow = "0.5.26"
